name: ap02
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8 # Adds Cupertino Icons

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # Recommended lints for good coding practices

flutter:
  uses-material-design: true # Ensures Material Icons are included
  assets:
    - assets/images/capa_splash.jpg
    - assets/images/capa_onboarding.jpg
    - assets/images/servicos/corte_cabelo.jpg # List of asset images

  # Custom fonts can be added here
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
